### ISSUE TITLE
Bug Fix List

### ISSUE THREAD

**Issue by orta** [artsy/energy#181]
- [ ] Shows / Artists covers not being synced ( did the URLs change? )
- [x] Analytics for Partner Size #174
- [x] Layout of select all sometimes off #180
- [x] Works that are public should include a link to artsy, plus a unique utr query
- [x] cc email being overridden by default partner email https://github.com/artsy/energy/issues/109
- [x] Disable email button for installation shots https://github.com/artsy/energy/issues/126
- [x] Back button not working second time in document viewer https://github.com/artsy/energy/issues/119
- [x] Some networking changes around the API sync health check https://github.com/artsy/energy/issues/198
- [x] Add support for sending user email in all analytics https://github.com/artsy/energy/issues/202

You got a freebie too in #182 

/cc @garrengotthardt @lucaderosso @ArtsyBecca

**Comment by garrengotthardt** [comment]
:+1:

**Comment by orta** [comment]
I've just tested the Show covers:

![screen shot 2016-02-23 at 8 23 58 pm](https://cloud.githubusercontent.com/assets/49038/13272607/82e78880-da6b-11e5-87ae-34fa1b563370.png)

When I changed it to a blue artwork and sync'd, it appeared in Folio before it did in the CMS:

![screen shot 2016-02-23 at 8 24 40 pm](https://cloud.githubusercontent.com/assets/49038/13272614/8f59e6d0-da6b-11e5-940f-747dc9e597a9.png)

Looks like Artists don't seem to work though.

**Comment by orta** [comment]
Looks like we've never supported Artist covers for CMS, considering that a feature, not a bug.

**Comment by orta** [comment]
Took a look into this, https://api.artsy.net/api/v1/artist/banksy - Artists use a completely different type of image type to Artworks, and Shows. Likely a larger job than I have at the this second ( note for self: the images would be classed as being in processing, and would require a new parser for `image_url` based Images. )

**Comment by dylanfareed** [comment]
what about the partner artist endpoint homeslice

On Tue, Feb 23, 2016 at 8:42 PM, Orta <notifications@github.com> wrote:
Took a look into this, https://api.artsy.net/api/v1/artist/banksy
[https://api.artsy.net/api/v1/artist/banksy] - Artists use a completely different type of image type to Artworks, and Shows.
Likely a larger job than I have at the this second ( note for self: the images
would be classed as being in processing, and would require a new parser for image_url based Images. )

—
Reply to this email directly or view it on GitHub
[https://github.com/artsy/energy/issues/181#issuecomment-188003524] .[https://github.com/notifications/beacon/AAMC2EKykLT626218UmuAHii8gNWKtm3ks5pnQHtgaJpZM4HgJHl.gif]

**Comment by orta** [comment]
Looks like same amount of work in parsing/image generation, but would give the real cover image ;) - we don't expose a capital I Image, so I'd probably need to make a version that does a subset of the work and cannot be asked for tiles etc.

for my reference: https://api.artsy.net/api/v1/partner/folio/artist/fennster-dog

**Comment by orta** [comment]
OK, https://github.com/artsy/energy/pull/187 adds support for "Works that are public should include a link to artsy, plus a unique utr query" - a link would look like: `https://www.artsy.net/artwork/mario-arroyave-divers-ii?utr=folio&partner=[partnerID]`

**Comment by garrengotthardt** [comment]
:+1: 

also just added a couple other existing bugs to this list that were already issued

**Comment by orta** [comment]
OK, all but the Artist/Shows cover image thing are done, I'm tempted to explore shipping a beta at the start of this week.

**Comment by garrengotthardt** [comment]
@orta 👌 closing this list

**Comment by orta** [comment]
👍
